config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :countries, only: [ :index ]
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  rescue_from HTTParty::ResponseError, with: :not_found

  def index
    @countries = []
    @countries = client.translations(params[:search]) if params[:search].present?
    @countries = @countries
                  .reject { |c| c["capital"].blank? }
                  .reject { |c| c["flags"].blank? }
  end

  def not_found
    render :not_found, status: :not_found
  end

  private

  def client
    @client ||= CountryApi.new
  end

  def filter_params
    params.fetch(:country, {}).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/countries/index.html.erb
<%= turbo_frame_tag "countries" do %>
  <% if @countries.blank? %>
    <p class="text-center text-gray-400">No countries found.</p>
  <% else %>
    <ul class="grid grid-cols-2 md:grid-cols-4 gap-4">
      <% @countries.each do |country| %>
        <li class="flex flex-row items-center gap-2 bg-gray-800 p-4 rounded-lg border border-gray-700">
          <div class="flex flex-col items-center gap-2">
            <%= image_tag(country.dig("flags", "png"), class: "h-16 object-cover") %>
            <% country.dig("capital").each do |capital| %>
              <p class="text-white font-bold"><%= capital %></p>
            <% end %>
          </div>
          <div class="flex flex-col">
            <p class="text-white"><%= country.dig("name", "common") %></p>
            <p class="text-gray-400"><%= country.dig("translations", "fra", "common") %></p>
            <p class="text-gray-400"><%= country.dig("translations", "deu", "common") %></p>
            <p class="text-gray-400"><%= country.dig("translations", "rus", "common") %></p>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/countries/not_found.html.erb
<%= turbo_frame_tag "countries" do %>
  <p class="text-center text-gray-400">No countries found.</p>
<% end %>

app/views/home/_countdown.html.erb
<div class="flex flex-col gap-5 w-full mb-12 border border-gray-700 p-5 rounded-lg bg-gray-800">
  <h1 class="px-1 text-center text-3xl tracking-tighter text-balance max-lg:font-medium lg:text-6xl text-white">Countdown</h1>
  <h2 class="px-1 text-center text-xl tracking-tighter text-balance max-lg:font-medium lg:text-3xl text-gray-300">A simple countdown using Stimulus</h2>
  <div data-controller="countdown reveal" data-reveal-hidden-class="hidden" class="flex flex-col gap-5 w-full" data-countdown-second-value="10" data-action="countdown:finished->reveal#show countdown:start->reveal#hide countdown:reset->reveal#hide">
    <div class="text-center text-6xl font-mono" data-countdown-target="display">00:00:00</div>
    <div class="flex justify-center gap-3">
      <button data-action="click->countdown#start" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Start</button>
      <button data-action="click->countdown#stop" class="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Stop</button>
      <button data-action="click->countdown#reset" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Reset</button>
    </div>
    <div data-reveal-target="item" class="hidden">
      <%= image_tag "text_timeup.png", class: "mx-auto" %>
    </div>
  </div>
</div>

app/views/home/_countries.html.erb
<div class="flex flex-col gap-5 w-full mb-12 border border-gray-700 p-5 rounded-lg bg-gray-800">
  <h1 class="px-1 text-center text-3xl tracking-tighter text-balance max-lg:font-medium lg:text-6xl text-white">Countries</h1>
  <h2 class="px-1 text-center text-xl tracking-tighter text-balance max-lg:font-medium lg:text-3xl text-gray-300">Fetch and display countries using an external API</h2>
  <%= form_with url: countries_path, method: :get,  data: { controller: "search reveal", reveal_hidden_class: "hidden", action: "input->search#submit turbo:submit-start->reveal#toggle turbo:submit-end->reveal#toggle", turbo_frame: "countries" } do |f| %>
    <div class="flex flex-col justify-center gap-3">
      <div class="flex mb-5 grow w-full justify-center gap-3">
        <%= f.text_field :search, data: { search_target: "input" }, placeholder: "Search countries...", class: "border w-1/2 border-gray-700 bg-gray-800 text-white py-2 px-4 rounded-lg" %>
      </div>
      <div class="flex flex-col justify-center min-h-[400px]">
        <div class="hidden" data-reveal-target="item">
          <div class="spinner mx-auto my-20"></div>
          <p class="text-center text-gray-400">We are searching for countries...</p>
        </div>
        <%= turbo_frame_tag "countries", data: { reveal_target: "item" } do %>
          <p class="text-center text-gray-400">No countries found.</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_photoswipe.html.erb
<div class="flex flex-col gap-5 w-full mb-12 border border-gray-700 p-5 rounded-lg bg-gray-800">
  <h1 class="px-1 text-center text-3xl tracking-tighter text-balance max-lg:font-medium lg:text-6xl text-white">Photoswipe</h1>
  <h2 class="px-1 text-center text-xl tracking-tighter text-balance max-lg:font-medium lg:text-3xl text-gray-300">Integrate with Photoswipe for a better image viewing experience</h2>
  <div data-controller="photoswipe" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
    <a href="<%= asset_path("dogs/1.jpg") %>" data-width="2848" data-height="4288">
      <%= image_tag "dogs/1.jpg", class: "w-full h-auto rounded-lg hover:scale-105 transition-transform duration-200", alt: "Dog 1" %>
    </a>
    <a href="<%= asset_path("dogs/2.jpg") %>" data-width="4032" data-height="3024">
      <%= image_tag "dogs/2.jpg", class: "w-full h-auto rounded-lg hover:scale-105 transition-transform duration-200", alt: "Dog 2" %>
    </a>
    <a href="<%= asset_path("dogs/3.jpg") %>" data-width="5784" data-height="3861">
      <%= image_tag "dogs/3.jpg", class: "w-full h-auto rounded-lg hover:scale-105 transition-transform duration-200", alt: "Dog 3" %>
    </a>
    <a href="<%= asset_path("dogs/4.jpg") %>" data-width="5184" data-height="3888">
      <%= image_tag "dogs/4.jpg", class: "w-full h-auto rounded-lg hover:scale-105 transition-transform duration-200", alt: "Dog 4" %>
    </a>
  </div>
</div>

app/views/home/_typewritter.html.erb
<div class="flex flex-col gap-5 w-full mb-12 border border-gray-700 p-5 rounded-lg bg-gray-800">
  <h1 class="px-1 text-center text-3xl tracking-tighter text-balance max-lg:font-medium lg:text-6xl text-white">Type writter</h1>
  <h2 class="px-1 text-center text-xl tracking-tighter text-balance max-lg:font-medium lg:text-3xl text-gray-300">A simple type writter effect</h2>
  <div data-controller="typewritter" class="flex flex-col gap-5 w-full" data-typewritter-speed-value="150">
    <div class="flex justify-center gap-3">
      <button data-action="click->typewritter#type" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Type</button>
      <button data-action="click->typewritter#reset" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Reset</button>
    </div>
    <p class="text-center font-typewriter" data-typewritter-target="text">This is a simple type writter effect using Stimulus. You can customize the text and the speed of the typing effect. Enjoy!</p>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex flex-col gap-5 w-full mb-12">
  <h1 class="px-1 text-center text-5xl tracking-tighter text-balance max-lg:font-medium lg:text-8xl text-white">Stimulus 101</h1>
  <h2 class="px-1 text-center text-xl tracking-tighter text-balance max-lg:font-medium lg:text-3xl text-gray-300">A simple demo to get you started</h2>

  <div class="flex flex-col items-center justify-center gap-3">
    <%= image_tag "qr-code.png", class: "flex h-32 w-32", alt: "QR Code" %>
    <p class="text-gray-400">Check the code on</p>
    <%= link_to "github.com/garciaf/stimulus-demo", "https://github.com/garciaf/stimulus-demo", class: "text-green-400 hover:underline" %>
  </div>

<%= render "typewritter" %>
<%= render "countdown" %>
<%= render "photoswipe" %>
<%= render "countries" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Demo Stimulus" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-dark text-white">
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>